Verifier audits
adamPetho/WalletWasabi pull request #5
Opened 2022-12-20 16:36 UTC by adamPetho

2022-12-21 14:34 UTC, molnard requested changes
cACK

2022-12-21 14:34 UTC, molnard commented on WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
> +					if (CoinVerifier.CoinVerifierAuditArchiver is not null)
It cannot be null.

2022-12-21 14:34 UTC, molnard commented on WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
> +		if (CoinVerifier.CoinVerifierAuditArchiver is not null)
It cannot be null.

2022-12-21 14:34 UTC, molnard commented on WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
> +						await CoinVerifier.CoinVerifierAuditArchiver.SaveAuditAsync(successfullyCheckedCoins, failedToCheckCoins, zeroCoordFeePayingCoins, round.Id.ToString(), possibleException, cancel).ConfigureAwait
We should not crash on any error, safer with a try-catch and Log.Error.

2022-12-21 14:34 UTC, molnard commented on WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
> +			await CoinVerifier.CoinVerifierAuditArchiver.SaveAuditAsync(successfullyCheckedCoins, failedToCheckCoins, Array.Empty<Coin>(), RoundId.ToString(), possibleException, CancellationToken.None).Config
We should not crash on any error, safer with a try-catch and Log.Error.

2023-01-03 10:06 UTC, molnard commented
@adamPetho what's up with this? Let me know if we can do pair prog on this.

2023-01-03 11:47 UTC, adamPetho commented
> @adamPetho what's up with this? Let me know if we can do pair prog on this.

@molnard Sure, we can do a pair prog today. I'm testing the PR at the moment.

2023-01-03 13:33 UTC, molnard reviewed
cACK

2023-01-03 15:35 UTC, lontivero commented
The whole coin verifier was introduced as a proactive defensive mechanism against threats consistent in accusing zkSNACKs  of not doing its best to prevent misuse of the coinjoins by criminals or other entities (to protect zkSNACKs and their people from the states, basically). 

You need to be able to **prove** that you are doing your part and that's why I insisted in having an audit log. Having the coin verifier without log is like having a XBox without a TV, it is completely useless. So, the audit log is a must but what it is for? It is for **keeping evidence** that allow us to **prove** that we have done what we have done.

If I want to prove you that I did something I need to provide you with detail information of that I did and you should expect something like this from me:

```
{
  Event: Coins batch verification
  Date: 2023-02-12,
  Time: 13:54:11.562,
  Verifier: CoinVerifier Inc
  API request: https://api.coinfirm.com/v3/reports/aml/standard/"
  API Key (Hashed): cee4b3becb142a859647dc7a4aa74392439ef3db6a658b439d363b77aee8d900 
  RiskFlags: [22, 34, 57, 58, 59, 60, 61, 62, 63, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 134, 144, 146, 150, 160, 165, 174, 177, 202, 242, 266, 267, 272, 274, 275, 308, 340, 342, 377, 380, 381, 390, 397]
  Addresses: [
     bc1qnxmnlduj6cpmcmh3vejvnuu637zsl5vf5se8z9,
     bc1qlu3fgjdrytdqe6kwg3tvnhh3p54dpear8yz9hp,
     bc1qzanm069nvjnznp6jk0cu9pgpuln08rlrvsq6rm,
     bc1qrc6f8atfajenat9vq9xhwctj0w2p08rhchlzwt,
     bc1qfzw5jkff4h2fq26ly0j3aac7mdzcemvp2mpg8r,
     bc1q2ms90yksazuekmlrpakst6exf8vc58q3s47mg2,
     bc1q39cpttfe8hu9nwsacp2aqpdtk6ypx89l53tgkz,
     bc1q52gxqcpzv8ha5gg0tdvwuscm7pdr7zwnxd4hck, 
     bc1qen2epxpz27yr7erv0hy9sgf4s0g53z7ah5ezsw,
     bc1qawg7exr7ukr3xd7fdawwlqpf9l5qfluwqj2540,
  ], 
  ReportId: 8H8Lu5jgGMhFMBB7zQc2WYX1AZrVV07oaCJDkTrlTSAGgysEPDAoHTepE0BMevQ0
  ReportDateTime: "2022-04-28T11:27:58.271Z",
  ReportBlockHeight": 733947,
  Addresses: [
  {
      bc1qnxmnlduj6cpmcmh3vejvnuu637zsl5vf5se8z9:  {
          Amount: 0.12345BTC,
          UsdValuation: 3451.34,
          Confirmations: 3769,
          RiskScore: 33,
          Info": [ "Inactive address", "Binance address" ],
          WhiteListed: true,
          Reason: [Low risk],
          PreviousVerificationDateTime: Never,
      },
      bc1qlu3fgjdrytdqe6kwg3tvnhh3p54dpear8yz9hp  {
          Amount: 324.7BTC,
          UsdValuation: 7,845,121.49,
          Confirmations: 7,
          RiskScore: 7896,
          Info": [ "Dark Market" ],
          WhiteListed: false,
          Reason: [High Risk, High Value, Low Maturity] 
     },
     ......
     ......
  },
  RiskScoreThreshold: 100
  ]
}
```

Not only that but also all changes in the verification criteria:

```
{
  Event: Verification config
  Date: 2023-02-12,
  Time: 13:54:14.21,
  Change: Coin Verification disabled
}
```

as well as:

```
{
  Event: Verification config
  Date: 2023-02-12,
  Time: 13:54:15.11,
  Change: Coin Verification enabled
}
```

and:

```
{
  Event: Verification config
  Date: 2023-02-12,
  Time: 13:54:15.11,
  Change:   RiskFlags [22, 34, 66] were removed
}
```

Also any error

```
{
  Event: Coins batch verification
  Date: 2023-02-12,
  Time: 13:54:11.562,
  Verifier: CoinVerifier Inc
  API request: https://api.coinfirm.com/v3/reports/aml/standard/"
  API Key (Hashed): cee4b3becb142a859647dc7a4aa74392439ef3db6a658b439d363b77aee8d900 
  RiskFlags: [22, 34, 57, 58, 59, 60, 61, 62, 63, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 134, 144, 146, 150, 160, 165, 174, 177, 202, 242, 266, 267, 272, 274, 275, 308, 340, 342, 377, 380, 381, 390, 397]
  Addresses: [
     bc1qnxmnlduj6cpmcmh3vejvnuu637zsl5vf5se8z9,
     bc1qlu3fgjdrytdqe6kwg3tvnhh3p54dpear8yz9hp,
     bc1qzanm069nvjnznp6jk0cu9pgpuln08rlrvsq6rm,
     ],
  Error: {
     Message: An existing connection was forcibly closed by a remote host
     Action: retry in x minutes
  }
}
```

2023-01-03 15:48 UTC, molnard commented
We got almost every piece of information. What is missing:

- Risk flag changes, which can be added as a list after every query as a reference
- Format is different, yours is more readable but cannot do statistics from it with excel. Thib is using that. 
- Coinverifier disabled is missing
- API request and key - I don't think it makes sense to log them. It is not changing right now. For most of the events, we are not using the API at all. 
- ReportId could be useful to add as a detail

What else?

2023-01-03 16:17 UTC, lontivero commented
I think we don't have every piece of information and I think some information that we have in the log is useless (roundid is the obvious one).

* API request is a must! It is the evidence and it changes in every request because it contains the address. It is perhaps the most important of all the data. API key is not so important and can be logged as a "Verification config" event, yes.

* Audit logs are for humans. What we have here is not a log but a list of csv designed not for keeping evidence of actions but to be have a list of addresses easy to import on excel to be used by one guy. To be clear, it doesn't matter what format we use, it should be readable by a human.

* ReportId is what allows us to prove that we made the request and got a response.

*  Failures are being ignored and they shouldn't. They are extremely important.

* Last time an utxo was verified and when that validation expires is also important.

2023-01-04 08:19 UTC, kiminuo reviewed
Partial review

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi.Backend/Global.cs
> +				coinVerifier = new(CoinJoinIdStore, coinVerifierApiClient, whitelist, CoordinatorParameters.RuntimeCoordinatorConfig, Path.Combine(CoordinatorParameters.CoordinatorDataDir, "CoinVerifierAudits"))
```suggestion
				coinVerifier = new(CoinJoinIdStore, coinVerifierApiClient, whitelist, CoordinatorParameters.RuntimeCoordinatorConfig, archiverDirectoryPath: Path.Combine(CoordinatorParameters.CoordinatorDataDir, "CoinVerifierAudits"));
```

though "audits" and "archiver directory path" sound like two different things to me

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
> +	public CoinVerifier(CoinJoinIdStore coinJoinIdStore, CoinVerifierApiClient apiClient, Whitelist whitelist, WabiSabiConfig wabiSabiConfig, string archiverDirectoryPath)
The second constructor does not set `CoinVerifierAuditArchiver` in any way which asks for a NRE. Generally there are three ways how to solve it:

1) Add `string archiverDirectoryPath` to the other ctor too
2) Make `CoinVerifierAuditArchiver` nullable
3) Allow to pass to an instance of `CoinVerifierAuditArchiver` right into `CoinVerifier` so that `CoinVerifierAuditArchiver` can be mocked in unit tests.

For testing purposes, the option 3 does seem good in general. Option 2 might be good too.

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
> +	public CoinVerifier(CoinJoinIdStore coinJoinIdStore, CoinVerifierApiClient apiClient, Whitelist whitelist, WabiSabiConfig wabiSabiConfig, string archiverDirectoryPath)
btw: I have noticed that `Arena` accepts `ICoinJoinIdStore` instead of `CoinJoinIdStore`. Would it be good to unify it and use the interface even here? In a follow-up PR.

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
> +				yield return new CoinVerifyInfo(false, coin, ApiResponseItem: null, CoinVerifierReason.FromCoinjoin);
Can be
```suggestion
				yield return new CoinVerifyInfo(ShouldBan: false, coin, ApiResponseItem: null, CoinVerifierReason.FromCoinjoin);
```

given that we touch this bit

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
> +				yield return new CoinVerifyInfo(false, coin, ApiResponseItem: null, CoinVerifierReason.Whitelisted);
```suggestion
				yield return new CoinVerifyInfo(ShouldBan: false, coin, ApiResponseItem: null, CoinVerifierReason.Whitelisted);
```

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
> +			// Step 2: Check if coin is from a coinjoin.
```suggestion
			// Step 2: Check if the coin is from a coinjoin transaction.
```

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
>  			{
L75: Is this missing ConfigureAwait(false)?

I mean `await foreach (var response in CoinVerifierApiClient.VerifyScriptsAsync(scriptsToCheck, linkedCts.Token))`

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
>  	public async IAsyncEnumerable<CoinVerifyInfo> VerifyCoinsAsync(IEnumerable<Coin> coinsToCheck, [EnumeratorCancellation] CancellationToken cancellationToken, string roundId = "")
Hm, personally I would make `roundId` mandatory argument (as it looks to me that it's optional just to save some typing in tests). Or at least I would change its default value to "Not provided" or something.

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
>  		Whitelist = whitelist;
The `Whitelist` class is incorrectly synchronized imho. If someone calls `CoinVerifier.VerifyCoinsAsync` in parallel, then we might crash in `Whitelist.WriteToFile()` with an exception or maybe even corrupt `WhitelistFilePath` contents.

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierAuditArchiver.cs
> +			await File.AppendAllLinesAsync(filePath, new[] { fileContent.ToString() }, cancellationToken).ConfigureAwait(false);
```suggestion
			await File.AppendAllLinesAsync(filePath, new[] { fileContent }, cancellationToken).ConfigureAwait(false);
```

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierAuditArchiver.cs
> +	private string ToLine(Coin coin, bool isBanned, string reason, string roundId, string? details = null)
Why not
```suggestion
	private string ToLine(Coin coin, bool isBanned, string reason, string roundId, string details = "")
```
?

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierAuditArchiver.cs
> +	private string ToLine(Coin coin, bool isBanned, string reason, string roundId, string? details = null)
And honestly the parameters could be ordered in some more meaningful way: 

* roundId
* coin
* isBanned
* reason
* details
?

2023-01-04 08:19 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierAuditArchiver.cs
> +		return $"{DateTimeOffset.UtcNow.ToLocalTime():yyyy-MM-dd HH:mm:ss.fff},{roundId},{coin.Outpoint},{coin.ScriptPubKey.GetDestinationAddress(Network.Main)},{isBanned},{coin.Amount},{reason},{details ?
Is this supposed to be CSV format? If yes, then you can pass in `details` with commas (https://github.com/adamPetho/WalletWasabi/pull/5/files#diff-4258351bea9e83b5cca5f0b3a68bf6f253fb3cdbb6848c3aa5dd25ed5879a191R51).

2023-01-04 10:51 UTC, adamPetho commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
>  			{
Yes, nice catch!

2023-01-04 10:54 UTC, adamPetho commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
>  	public async IAsyncEnumerable<CoinVerifyInfo> VerifyCoinsAsync(IEnumerable<Coin> coinsToCheck, [EnumeratorCancellation] CancellationToken cancellationToken, string roundId = "")
Well, it's only for one logging line, so when this Auditor gets finalized, we might be able to remove this param altogether.

2023-01-04 11:05 UTC, adamPetho commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
>  		Whitelist = whitelist;
A lock would solve this, right?

2023-01-04 11:19 UTC, adamPetho commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierAuditArchiver.cs
> +	private string ToLine(Coin coin, bool isBanned, string reason, string roundId, string? details = null)
Well, we might remove the roundId from the audit, then the params order will be as you described above.

But details don't need to be nullable, so thank you, I will make the change.

2023-01-04 11:43 UTC, adamPetho commented on WalletWasabi.Backend/Global.cs
> +				coinVerifier = new(CoinJoinIdStore, coinVerifierApiClient, whitelist, CoordinatorParameters.RuntimeCoordinatorConfig, Path.Combine(CoordinatorParameters.CoordinatorDataDir, "CoinVerifierAudits"))
Hmm, yes `auditsDirectoryPath` would be a better param name IMO.

2023-01-04 11:46 UTC, adamPetho commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierAuditArchiver.cs
> +		return $"{DateTimeOffset.UtcNow.ToLocalTime():yyyy-MM-dd HH:mm:ss.fff},{roundId},{coin.Outpoint},{coin.ScriptPubKey.GetDestinationAddress(Network.Main)},{isBanned},{coin.Amount},{reason},{details ?
Well, these audits will be fed to an excel table and AFAIK we want to have one details column, and not give every detail its own column.

2023-01-04 13:46 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierAuditArchiver.cs
> +		return $"{DateTimeOffset.UtcNow.ToLocalTime():yyyy-MM-dd HH:mm:ss.fff},{roundId},{coin.Outpoint},{coin.ScriptPubKey.GetDestinationAddress(Network.Main)},{isBanned},{coin.Amount},{reason},{details ?
Then it is CVS format. You can even change `,` to `;` and Excel can still load it.

2023-01-04 13:46 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
>  		Whitelist = whitelist;
Yes, imo it should be guarded by a lock.

2023-01-05 12:41 UTC, adamPetho commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
>  		Whitelist = whitelist;
We use `ConcurrentDictionary`, so adding and removing from the `dict` should be protected, right? 

So, I only should guard the function where we are getting the values to write it to the file right? (Perhaps also when we count the values)

2023-01-05 13:54 UTC, kiminuo commented on WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
>  		Whitelist = whitelist;
Ideally, it should be synchronized properly. The easiest way is to switch from `ConcurrentDictionary` to `Dictionary` and have a simple lock that locks the dictionary + the `ToFile` method. 

As you say it, it sounds like one can modify the ConcurrentDictionary from one thread and call `ToFile` from other and in the process, you won't crash but data may be inconsistent which personally I find even worse than crashing.

2023-01-05 14:17 UTC, molnard commented
Sorry for the interference but I had to implement this as well which will surely cause some conflicts here, but IMO it is cleaner and easier to build upon the audit. https://github.com/molnard/WalletWasabi/pull/45

2023-01-23 11:42 UTC, adamPetho commented
Superseded by https://github.com/adamPetho/WalletWasabi/pull/6

2023-01-23 11:42 UTC, closed without merging